### ISSUE TITLE
How to generate folds.csv file?

### ISSUE THREAD

**Issue by rohitgr7** [oleg-yaroshevskiy/quest_qa_labeling#14]
How did you generate [folds.cv](https://github.com/oleg-yaroshevskiy/quest_qa_labeling/blob/master/step3_model1_bert_code/data/folds.csv) file in [step3_model1_bert_code](https://github.com/oleg-yaroshevskiy/quest_qa_labeling/tree/master/step3_model1_bert_code/data)? Is it basic `GroupKFold` or something else?

**Comment by Yorko** [comment]
I don't see that it's used anywhere in the code, sorry for the confusion.
